version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.16.0
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "9901"
      - "10000"
    ports:
    - "9901:9901"
    - "10000:10000"

networks:
  envoymesh: {}
