version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.14.1
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./istio-jwt-tools/jwks.json:/etc/envoy/jwks.json
    networks:
      - envoymesh
    expose:
      - "8080"
      - "8081"
    ports:
    - "8080:8080"
    - "8081:8081"

  app:
    image: kennethreitz/httpbin
    networks:
      - envoymesh
    expose:
      - "80"

networks:
  envoymesh: {}
